spring:
  messages:
    basename: messages,demo
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  skr:
    security:
      renewRefreshToken: false
      jwtPrincipalClass: demo.skr.SimpleJwtPrincipal

memcached.cache:
  servers: 192.168.1.120:11211
  mode: static
  expirations: 86400, cache_name1:3600, cache_name2:108000

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000