spring:
  datasource:
    url: "jdbc:hsqldb:mem:local;sql.syntax_pgs=true"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
    enabled: false

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR

tsf:
  swagger:
    enabled: false