spring:
  datasource:
    url: "jdbc:hsqldb:mem:testdb;sql.syntax_pgs=true"
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR

tsf:
  swagger:
    enabled: false

skr:
  security:
    jwtPrincipalClazz: org.skr.security.User