server:
  port: 8001
spring:
  datasource:
    url: "jdbc:hsqldb:mem:local;sql.syntax_pgs=true"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
    enabled: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR

tsf:
  swagger:
    enabled: false