spring:
  datasource:
    url: "jdbc:hsqldb:mem:testdb;sql.syntax_pgs=true"
  jpa:
    show-sql: true
  sleuth:
    enabled: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR

tsf:
  swagger:
    enabled: false

skr:
  security:
    jwtPrincipalClazz: org.skr.security.SimpleJwtPrincipal