spring:
  skr:
    security:
      renew-refresh-token: false
      skip-urls:
        - /actuator/**
        - /auth/**
        - /registry/**
        - /public/**
      login-token:
        secret: sKrRrRrRrRrRrRrRrLogin
        expiration: 10080 # default 7 days
      access-token:
        secret: sKrRrRrRrRrRrRrRrAccess
        expiration: 10    # 5 mins
        prefix: Bearer-
        header: access-token
      refresh-token:
        secret: sKrRrRrRrRrRrRrRrRefresh
        expiration: 30    # 30 mins
        prefix: Refresh-
        header: refresh-token
      robot-token:
        secret: sKrRrRrRrRrRrRrRrRobot
        prefix: Robot-
        username: ∆coreRobot∆
      train-token:
        secret: sKrRrRrRrRrRrRrRrTrain
        prefix: Train-