spring:
  skr:
    security:
      renew-refresh-token: false
      skip-urls:
        - /actuator/**
        - /auth/**
        - /registry/**
        - /public/**
      login-token:
        secret: sKrRrRrRrRrRrRrRrLogin
        expiration: 10080 # 7 days
        header: login-token
      access-token:
        secret: sKrRrRrRrRrRrRrRrAccess
        expiration: 10    # 5 mins
        prefix: Bearer-
        header: access-token
      refresh-token:
        secret: sKrRrRrRrRrRrRrRrRefresh
        expiration: 30    # 30 mins
        header: refresh-token
      ghost-token:
        secret: sKrRrRrRrRrRrRrRrRobot
        prefix: Robot-