spring:
  skr:
    security:
      renewRefreshToken: false
      skip-urls:
        - /actuator/**
        - /login
        - /refresh-token
        - /registry/**
      loginToken:
        secret: sKrRrRrRrRrRrRrRrLogin
        expiration: 10080 # default 7 days
      accessToken:
        secret: sKrRrRrRrRrRrRrRrAccess
        expiration: 10    # 5 mins
        prefix: Bearer-
        header: access-token
      refreshToken:
        secret: sKrRrRrRrRrRrRrRrRefresh
        expiration: 30    # 30 mins
        prefix: Refresh-
        header: refresh-token
      robotToken:
        secret: sKrRrRrRrRrRrRrRrRobot
        prefix: Robot-
        username: ∆coreRobot∆
      trainToken:
        secret: sKrRrRrRrRrRrRrRrTrain
        prefix: Train-