spring:
  skr:
    security:
      renewRefreshToken: false
      skip-urls:
        - /actuator/**
        - /login
        - /refresh-token
        - /registry/**
      accessToken:
        secret: sKrRrRrRrRrRrRrRrAccess
        expiration: 1200000
        prefix: Bearer-
        header: access-token
      refreshToken:
        secret: sKrRrRrRrRrRrRrRrRefresh
        expiration: 3600000
        prefix: Refresh-
        header: refresh-token
      robotToken:
        secret: sKrRrRrRrRrRrRrRrRobot
        prefix: Robot-
        username: ∆coreRobot∆
      trainToken:
        secret: sKrRrRrRrRrRrRrRrTrain
        prefix: Train-