@startuml
title Request
AppClient -> AppServer1: I want to access API <font color=blue>x</font>, \nand here is my <font color=red>request token</font>
AppServer1 -> JwtAuthenticationFilter: Decode this <font color=red>access token</font> to see who it is.
JwtAuthenticationFilter --> AppServer1: Ops...principle not found
AppServer1 -->x AppClient: 401, get out!
JwtAuthenticationFilter --> AppServer1: Ops...token expired
AppServer1 -->x AppClient: Show me your <font color=red>refresh token</font> to\nexchange a new <font color=red>access token</font>.
JwtAuthenticationFilter -> AppServer1: The token is all right and here is the principle.
AppServer1 -> PermissionCheckingAspect: Check if this principle has permission to access API <font color=blue>x</font>
PermissionCheckingAspect --> AppServer1: Ops...this principle <b>HAS NO</b> permission to access this API.
AppServer1 -->x AppClient: 403, get out!
PermissionCheckingAspect -> AppServer1: This principle <b>HAS</b> permission to access this API.
AppServer1 -> AppServer2: I want to access API <font color=blue>y</font>, and here is user's <font color=red>train token</font>
AppServer2 -> AppServer1: 200, request result
AppServer1 -->x AppClient: 200, request result
@enduml