spring:
  datasource:
    url: "jdbc:hsqldb:mem:local;sql.syntax_pgs=true"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl: ERROR

tsf:
  swagger:
    enabled: false